// Parte B: Job a Malaquías (días 144-308) — poéticos y proféticos
const PLAN_FULL_B = [
["Job",1,3,"Job, hombre justo, lo pierde todo en una prueba que ignora; mantiene su fe al inicio, pero luego lamenta amargamente su existencia."],
["Job",4,6,"Elifaz sugiere que Job sufre por algún pecado; Job responde con angustia, defendiendo su integridad y clamando a Dios."],
["Job",7,9,"Job describe su dolor y reconoce la grandeza de Dios, pero no entiende por qué sufre ni cómo presentar su caso ante él."],
["Job",10,12,"Job clama a Dios sin entender; Zofar lo acusa, y Job responde que la sabiduría y el poder pertenecen al Señor."],
["Job",13,15,"Job anhela exponer su caso ante Dios y mantiene su esperanza; Elifaz vuelve a acusarlo de orgullo e impiedad."],
["Job",16,18,"Job se siente atacado y abandonado, pero confía en un testigo en los cielos; Bildad insiste en el castigo del malvado."],
["Job",19,21,"En medio del dolor, Job declara 'yo sé que mi Redentor vive'; observa que a veces los malvados prosperan en esta vida."],
["Job",22,24,"Elifaz acusa a Job de maldad; Job anhela hallar a Dios y confía en que saldrá como oro tras la prueba."],
["Job",25,27,"Bildad habla brevemente; Job exalta el poder de Dios sobre la creación y mantiene firme su integridad."],
["Job",28,30,"Job reflexiona sobre dónde se halla la sabiduría: en el temor de Dios; recuerda sus días de honra y lamenta su miseria actual."],
["Job",31,33,"Job hace un juramento final de inocencia; el joven Eliú interviene afirmando que Dios habla y enseña por medio del sufrimiento."],
["Job",34,36,"Eliú defiende la justicia y la grandeza de Dios, sosteniendo que él no hace mal y usa la aflicción para corregir."],
["Job",37,39,"Eliú exalta las maravillas de Dios; el Señor responde desde el torbellino con preguntas sobre la creación que humillan a Job."],
["Job",40,42,"Dios describe a Behemot y Leviatán, revelando su poder; Job se arrepiente, y el Señor lo restaura y le devuelve el doble."],

["Salmos",1,3,"Bienaventurado quien medita en la ley; aunque las naciones se rebelan, Dios reina y protege al que en él confía."],
["Salmos",4,6,"Oraciones de confianza y súplica ante la angustia y los enemigos; el creyente halla paz y descanso en el Señor."],
["Salmos",7,9,"David clama por justicia y se asombra de la gloria de Dios en la creación; el Señor juzga con rectitud a los pueblos."],
["Salmos",10,12,"Ante la maldad y la opresión, el salmista confía en que Dios defiende a los humildes y guarda sus palabras puras."],
["Salmos",13,15,"Entre el '¿hasta cuándo?' y la confianza, el salmista describe a quien habita con Dios: el de conducta íntegra y veraz."],
["Salmos",16,18,"Dios es la herencia y el refugio del creyente; un gran cántico celebra al Señor como roca y libertador en la batalla."],
["Salmos",19,21,"La creación y la ley revelan a Dios; oraciones por el rey y acción de gracias por la salvación que el Señor concede."],
["Salmos",22,24,"El salmo del sufrimiento ('¿por qué me has desamparado?'), el Señor como pastor que nada falta, y el Rey de gloria que entra."],
["Salmos",25,27,"Súplicas de perdón, integridad y protección; David confía en el Señor como su luz, su salvación y su fortaleza."],
["Salmos",28,30,"La voz poderosa de Dios y la acción de gracias por la sanidad: el llanto dura una noche pero la alegría viene a la mañana."],
["Salmos",31,33,"'En tu mano encomiendo mi espíritu'; la dicha del perdón y un cántico nuevo a la palabra creadora y fiel de Dios."],
["Salmos",34,36,"'Gustad y ved que el Señor es bueno'; consejo a no envidiar a los malos y confiar en la misericordia de Dios."],
["Salmos",37,39,"No te alteres por los malvados; confía y haz el bien; confesión de la fragilidad humana y la esperanza puesta en Dios."],
["Salmos",40,42,"Gratitud por ser sacado del lodo y oración en la enfermedad; el alma sedienta de Dios como el ciervo brama por las aguas."],
["Salmos",43,45,"Anhelo de la presencia de Dios, memoria de sus obras pasadas, y un cántico real que celebra al rey y su gloria."],
["Salmos",46,48,"'Dios es nuestro amparo y fortaleza'; Rey de toda la tierra, defensa segura de su ciudad, digno de alabanza."],
["Salmos",49,51,"La riqueza no redime la vida; Dios juzga con justicia, y el gran salmo de arrepentimiento de David: 'crea en mí un corazón limpio'."],
["Salmos",52,54,"Frente a la traición y la insensatez, el salmista confía en la misericordia de Dios y en que él es su ayudador."],
["Salmos",55,57,"Oraciones en medio del peligro y la angustia; el creyente echa su carga sobre el Señor y se refugia bajo sus alas."],
["Salmos",58,60,"Clamor por justicia ante los poderosos injustos y oración por liberación; solo en Dios hay verdadera victoria."],
["Salmos",61,63,"El alma reposa solo en Dios, su roca y salvación; el salmista lo busca de madrugada con sed profunda de su presencia."],
["Salmos",64,66,"Confianza ante los enemigos y alabanza por la bondad de Dios en la creación y en la historia de su pueblo."],
["Salmos",67,69,"Llamado a que las naciones alaben a Dios; el Dios que sostiene a los suyos, y un clamor desde aguas profundas de angustia."],
["Salmos",70,72,"Súplica por pronta ayuda, la confianza del anciano que esperó en Dios desde joven, y oración por un reinado justo."],
["Salmos",73,75,"El salmista lucha con la prosperidad de los malos hasta entrar al santuario; Dios es el juez que levanta y humilla."],
["Salmos",76,78,"Dios es temible y poderoso; en la noche de angustia se recuerdan sus obras, y se repasa la historia de Israel y su fidelidad."],
["Salmos",79,81,"Lamento por Jerusalén y súplica de restauración; llamado a escuchar a Dios que sacó a su pueblo de Egipto."],
["Salmos",82,84,"Dios juzga a los jueces injustos; clamor ante las naciones, y el anhelo por sus moradas: 'cuán amables son tus moradas'."],
["Salmos",85,87,"Súplica de avivamiento y restauración; oración de confianza en el Dios bueno, y la gloria de Sión, ciudad de Dios."],
["Salmos",88,90,"Un lamento desde la oscuridad y un cántico sobre el pacto con David; Moisés medita en la eternidad de Dios y la brevedad humana."],
["Salmos",91,93,"Quien habita al abrigo del Altísimo halla refugio seguro; alabanza por la fidelidad de Dios, cuyo trono y reinado son eternos."],
["Salmos",94,96,"Dios juzga con justicia; venid, adoremos al Rey; cantad un cántico nuevo, porque grande es el Señor entre las naciones."],
["Salmos",97,99,"El Señor reina con justicia y santidad; cantad alabanzas al Rey, exaltadle, porque santo es y ama el derecho."],
["Salmos",100,102,"Entrad por sus puertas con acción de gracias; canto a la misericordia y la justicia, y oración del afligido ante el Dios eterno."],
["Salmos",103,105,"Bendice, alma mía, al Señor, que perdona y sana; la majestad del Creador que sostiene la vida y su fidelidad en la historia."],
["Salmos",106,108,"Confesión de la rebeldía de Israel siempre perdonada; gratitud de los redimidos que Dios libró de toda angustia."],
["Salmos",109,111,"Clamor del calumniado, el Mesías Rey y Sacerdote a la diestra de Dios, y alabanza por las obras grandes del Señor."],
["Salmos",112,114,"La dicha del que teme a Dios, alabanza al Señor que levanta al pobre, y el recuerdo del éxodo cuando el mar huyó."],
["Salmos",115,117,"Solo a Dios la gloria, no a los ídolos; amor por el Señor que escucha, y llamado a todas las naciones a alabarle."],
["Salmos",118,120,"Gratitud por la misericordia eterna y la piedra angular desechada; canto a la Palabra y clamor por la paz."],
["Salmos",121,123,"El Señor es tu guardador que no duerme; gozo de subir a su casa, y los ojos puestos en Dios esperando su gracia."],
["Salmos",124,126,"Si el Señor no hubiera estado de nuestro lado; confianza inquebrantable como el monte Sión, y el gozo de la restauración."],
["Salmos",127,129,"Si el Señor no edifica, en vano se trabaja; bendición del hogar temeroso de Dios y resistencia ante la aflicción."],
["Salmos",130,132,"Desde lo profundo clamo, en él hay redención; el alma serena que confía como un niño, y la memoria del pacto con David."],
["Salmos",133,135,"La dicha de la unidad fraternal, el llamado a bendecir al Señor de noche, y alabanza al Dios que obra maravillas."],
["Salmos",136,138,"Su misericordia es para siempre; el lamento del exilio junto a los ríos de Babilonia, y gratitud por la fidelidad de Dios."],
["Salmos",139,141,"Dios me conoce y me formó por completo; oración para ser examinado y guardado del mal en palabras y acciones."],
["Salmos",142,144,"Clamor desde la angustia y confianza en el Dios fiel que entrena las manos para la lucha y libra de todo mal."],
["Salmos",145,147,"Cánticos de alabanza a la grandeza y bondad de Dios, que sostiene a los caídos, sana a los quebrantados y sustenta la creación."],
["Salmos",148,150,"El gran final de alabanza: cielos, tierra y todo cuanto respira alabe al Señor por su poder y su amor eterno."],

["Proverbios",1,3,"El temor del Señor es el principio de la sabiduría; el padre exhorta al hijo a buscar entendimiento y confiar en Dios de todo corazón."],
["Proverbios",4,6,"Llamados a atesorar la sabiduría, guardar el corazón y evitar la pereza, la inmoralidad y las trampas que destruyen la vida."],
["Proverbios",7,9,"Advertencia contra la seducción; la sabiduría clama en las calles e invita a su banquete, mientras la insensatez lleva a la muerte."],
["Proverbios",10,12,"Contrastes entre el justo y el impío en el hablar, el trabajo y la integridad; la boca del justo es fuente de vida."],
["Proverbios",13,15,"Dichos sobre la diligencia, la disciplina y la lengua; la respuesta blanda quita la ira y el corazón alegre es buena medicina."],
["Proverbios",16,18,"El corazón y los planes ante Dios; la humildad precede a la honra, y la lengua tiene poder de vida o muerte."],
["Proverbios",19,21,"Sabiduría sobre la pobreza y la riqueza, la pereza y la justicia; el corazón del hombre traza su camino, pero Dios dirige sus pasos."],
["Proverbios",22,24,"Buen nombre vale más que riquezas; instrucción de los hijos y dichos de los sabios sobre prudencia y no envidiar a los malos."],
["Proverbios",25,27,"Proverbios recopilados por los hombres de Ezequías sobre la convivencia, la moderación y el valor de la amistad sincera."],
["Proverbios",28,31,"Contrastes entre justos y malvados; el cierre elogia a la mujer virtuosa cuyo valor supera al de las joyas."],

["Eclesiastés",1,3,"El Predicador busca sentido en placeres, sabiduría y trabajo, y todo le parece vanidad; hay un tiempo para todo bajo el sol."],
["Eclesiastés",4,6,"Reflexiones sobre la opresión, la soledad y la riqueza vacía; vale más la sencillez y el contentamiento que la avaricia."],
["Eclesiastés",7,9,"Sabiduría ante la vida y la muerte; aunque no entendamos todo, conviene disfrutar lo bueno y temer a Dios."],
["Eclesiastés",10,12,"El cierre llama a recordar al Creador en la juventud; la conclusión: teme a Dios y guarda sus mandamientos, ese es el deber del hombre."],

["Cantares",1,3,"Un poema de amor entre los esposos que se buscan y se admiran mutuamente, celebrando la belleza del amor sincero."],
["Cantares",4,6,"El esposo alaba a la amada y ella le corresponde; el amor se expresa con ternura, anhelo y entrega mutua."],
["Cantares",7,8,"Culmina el canto al amor, fuerte como la muerte; un amor que no se compra y que muchas aguas no pueden apagar."],

["Isaías",1,3,"Isaías denuncia la rebeldía de Judá y llama al arrepentimiento; anuncia juicio, pero también un futuro de paz para Sión."],
["Isaías",4,6,"El renuevo del Señor y la viña que decepciona; Isaías ve la santidad de Dios, confiesa su pecado y es enviado como profeta."],
["Isaías",7,9,"En medio de la amenaza, se anuncia la señal del Emanuel y el niño que nacerá: Príncipe de paz, cuyo reino no tendrá fin."],
["Isaías",10,12,"Juicio sobre Asiria y promesa de un renuevo del tronco de Isaí; el reino mesiánico de justicia y un cántico de salvación."],
["Isaías",13,15,"Profecías de juicio contra Babilonia y otras naciones, mostrando que Dios es soberano sobre todos los pueblos de la tierra."],
["Isaías",16,18,"Continúan los oráculos contra Moab, Damasco y otras naciones, advirtiendo del juicio y la fragilidad del poder humano."],
["Isaías",19,21,"Juicio sobre Egipto y otras naciones, con la promesa sorprendente de que Egipto y Asiria también serán bendecidos por Dios."],
["Isaías",22,24,"Oráculos sobre Jerusalén y Tiro; una visión del juicio de Dios sobre toda la tierra antes de su reinado glorioso."],
["Isaías",25,27,"Cánticos de confianza: Dios enjugará toda lágrima y vencerá la muerte; un himno por la ciudad fuerte y la viña del Señor."],
["Isaías",28,30,"Ayes contra los líderes ebrios y las alianzas vanas; Dios llama a confiar en él, la piedra angular, y no en Egipto."],
["Isaías",31,33,"Necio es confiar en Egipto y no en Dios; se anuncia un rey justo y la restauración cuando el Señor se levante a salvar."],
["Isaías",34,36,"Juicio sobre las naciones y el florecer del desierto redimido; comienza el relato del asedio asirio a Jerusalén."],
["Isaías",37,39,"Ezequías ora y Dios libra a Jerusalén de Asiria; el rey es sanado, pero su orgullo ante Babilonia anticipa el exilio."],
["Isaías",40,42,"Palabras de consuelo: preparad el camino del Señor; el Dios eterno da fuerzas al cansado, y presenta a su Siervo escogido."],
["Isaías",43,45,"No temas, yo te redimí; Dios es el único Salvador, anuncia lo nuevo, y llama por nombre a Ciro para liberar a su pueblo."],
["Isaías",46,48,"Los ídolos de Babilonia caen, la ciudad será humillada, y Dios llama a su pueblo a salir y escuchar al único Dios verdadero."],
["Isaías",49,51,"El Siervo es luz a las naciones; Dios no olvida a Sión, consuela a los suyos y los anima a despertar a la salvación."],
["Isaías",52,54,"El Siervo sufriente lleva el pecado de muchos y por sus llagas somos sanados; Sión es consolada como esposa restaurada."],
["Isaías",55,57,"Venid a las aguas sin dinero; buscad al Señor mientras puede ser hallado; promesa para los extranjeros y consuelo al humilde."],
["Isaías",58,60,"El ayuno que Dios quiere es la justicia; la confesión del pecado, y la promesa de luz y gloria sobre Sión restaurada."],
["Isaías",61,63,"El Espíritu del Señor anuncia buenas nuevas a los pobres; gozo en Dios, intercesión por Sión y memoria de su misericordia."],
["Isaías",64,66,"Clamor para que Dios descienda; él crea cielos y tierra nuevos, mira al humilde y de corazón contrito, y reúne a las naciones."],

["Jeremías",1,3,"Dios llama al joven Jeremías como profeta; denuncia el abandono de Judá, que cambió a Dios por ídolos, y llama a volver."],
["Jeremías",4,6,"Jeremías anuncia el juicio que viene del norte por la maldad de Judá, y llora por un pueblo que no quiere arrepentirse."],
["Jeremías",7,9,"En la puerta del templo, Jeremías advierte que el culto sin justicia no salva; lamenta la corrupción y la falsedad del pueblo."],
["Jeremías",10,12,"Contra los ídolos vanos frente al Dios vivo; el pacto quebrantado, complots contra Jeremías y su queja ante la prosperidad de los malos."],
["Jeremías",13,15,"Señales del juicio venidero por la sequía y la rebeldía; Jeremías intercede, pero el juicio es inevitable, y él sufre por su misión."],
["Jeremías",16,18,"La vida solitaria del profeta como señal; confianza en el Señor frente al corazón engañoso; la lección del alfarero y el barro."],
["Jeremías",19,21,"La vasija rota anuncia juicio; Jeremías es perseguido y se queja con dolor, pero sigue proclamando la palabra de Dios."],
["Jeremías",22,24,"Juicio sobre los reyes infieles y los falsos pastores; promesa del Renuevo justo de David y la visión de los higos buenos y malos."],
["Jeremías",25,27,"Se anuncian setenta años de exilio en Babilonia; Jeremías casi muere por profetizar, y llama a someterse al yugo de Babilonia."],
["Jeremías",28,30,"Frente a los falsos profetas, Jeremías escribe a los exiliados a buscar el bien de la ciudad; promesa de restauración futura."],
["Jeremías",31,33,"El nuevo pacto escrito en el corazón; Dios promete restaurar a su pueblo, y confirma su fidelidad eterna pese al juicio presente."],
["Jeremías",34,36,"La infidelidad con los esclavos liberados; el ejemplo de los recabitas, y el rey que quema el rollo de la palabra de Dios."],
["Jeremías",37,39,"Jeremías es encarcelado y echado en una cisterna por su mensaje; Jerusalén cae finalmente ante Babilonia como fue advertido."],
["Jeremías",40,42,"Tras la caída, queda un remanente; Gedalías es asesinado, y el pueblo pide consejo a Jeremías pero rechaza obedecer a Dios."],
["Jeremías",43,45,"El remanente huye a Egipto desobedeciendo; Jeremías advierte el juicio que los alcanzará allí, y da una promesa a Baruc."],
["Jeremías",46,48,"Profecías contra Egipto, los filisteos y Moab; Dios es soberano sobre todas las naciones y juzga su orgullo."],
["Jeremías",49,52,"Juicio contra Amón, Edom y otras naciones, y la larga sentencia contra Babilonia; el relato final de la caída de Jerusalén."],

["Lamentaciones",1,3,"Jeremías llora la destrucción de Jerusalén; en medio del dolor brilla la esperanza: las misericordias de Dios son nuevas cada mañana."],
["Lamentaciones",4,5,"Continúa el lamento por la ciudad caída y el sufrimiento del pueblo; termina con una súplica para que Dios los restaure."],

["Ezequiel",1,3,"Ezequiel ve la gloria de Dios en una visión deslumbrante junto a los exiliados, y es llamado a ser centinela de Israel."],
["Ezequiel",4,6,"Mediante señales dramáticas, Ezequiel anuncia el asedio de Jerusalén y el juicio sobre la idolatría del pueblo."],
["Ezequiel",7,9,"Llega el fin sobre la tierra; Ezequiel ve la idolatría en el templo y cómo la gloria de Dios comienza a apartarse."],
["Ezequiel",10,12,"La gloria de Dios abandona el templo; el profeta representa el exilio y desmiente a quienes creen que no habrá juicio."],
["Ezequiel",13,15,"Contra los falsos profetas y la idolatría del corazón; Jerusalén es como una vid inútil destinada al fuego."],
["Ezequiel",16,18,"Jerusalén como esposa infiel a quien Dios amó; cada uno es responsable de su propio pecado, y Dios no quiere la muerte del malvado."],
["Ezequiel",19,21,"Lamento por los príncipes de Israel; el historial de rebeldía del pueblo y la espada del juicio que Dios desenvaina."],
["Ezequiel",22,24,"Los pecados de Jerusalén y sus líderes; la parábola de las dos hermanas infieles y la olla, anunciando el asedio final."],
["Ezequiel",25,27,"Juicio contra las naciones vecinas que se gozaron en la caída de Israel, y lamento por la rica y orgullosa Tiro."],
["Ezequiel",28,30,"Juicio sobre el príncipe de Tiro y sobre Egipto; el orgullo de los poderosos es humillado ante la soberanía de Dios."],
["Ezequiel",31,33,"Egipto cae como un gran árbol; Ezequiel es de nuevo centinela, y al llegar la noticia de la caída de Jerusalén, su boca se abre."],
["Ezequiel",34,36,"Contra los malos pastores, Dios mismo pastoreará a su pueblo; promete un corazón nuevo y un espíritu nuevo, y restaurará la tierra."],
["Ezequiel",37,39,"La visión de los huesos secos que reviven anuncia la resurrección de Israel; Dios reunirá a su pueblo y vencerá a sus enemigos."],
["Ezequiel",40,42,"En una visión, Ezequiel recorre un nuevo templo medido con detalle, símbolo de la presencia restaurada de Dios."],
["Ezequiel",43,45,"La gloria de Dios regresa al templo; se ordenan el altar, el culto y las porciones de la tierra para el servicio santo."],
["Ezequiel",46,48,"Normas para la adoración; del templo brota un río que da vida por donde pasa, y se reparte la tierra: 'el Señor está allí'."],

["Daniel",1,3,"Daniel y sus amigos son fieles a Dios en Babilonia; interpreta el sueño del rey, y tres jóvenes son librados del horno de fuego."],
["Daniel",4,6,"Nabucodonosor es humillado y reconoce a Dios; Belsasar ve la escritura en la pared, y Daniel es librado del foso de los leones."],
["Daniel",7,9,"Visiones de reinos y del Hijo del Hombre; la profecía de las setenta semanas mientras Daniel ora por su pueblo."],
["Daniel",10,12,"Una última visión sobre conflictos futuros y el tiempo del fin; promesa de resurrección y recompensa para los fieles."],

["Oseas",1,3,"Por orden de Dios, Oseas se casa con una mujer infiel como imagen del amor de Dios por un Israel adúltero que él no abandona."],
["Oseas",4,6,"Dios acusa a Israel de falta de conocimiento y fidelidad; llama al arrepentimiento: 'misericordia quiero, y no sacrificio'."],
["Oseas",7,9,"Israel siembra viento y siega tempestad; su idolatría y sus alianzas traen el juicio que el profeta anuncia con dolor."],
["Oseas",10,12,"Pese a la rebeldía, Dios recuerda su amor desde Egipto; llama a sembrar justicia y volver al Señor de todo corazón."],
["Oseas",13,14,"Advertencia final por la idolatría, pero termina con una invitación tierna: 'volved al Señor', que sana la rebeldía y ama de gracia."],

["Joel",1,3,"Una plaga de langostas anuncia el día del Señor; Joel llama al arrepentimiento, promete el derramamiento del Espíritu y la restauración."],

["Amós",1,3,"Amós denuncia los crímenes de las naciones y de Israel; Dios no pasa por alto la injusticia de su propio pueblo escogido."],
["Amós",4,6,"Israel no volvió a Dios pese a las advertencias; ¡ay de los que viven en lujo ignorando la opresión! Buscad a Dios y vivid."],
["Amós",7,9,"Visiones de juicio y la confrontación con el sacerdote; tras el juicio inevitable, Dios promete restaurar el reino caído de David."],

["Abdías",1,1,"Abdías anuncia el juicio sobre Edom por su orgullo y por gozarse en la desgracia de su hermano Israel; el reino será del Señor."],

["Jonás",1,4,"Jonás huye del llamado de Dios, es tragado por un gran pez y luego predica a Nínive, que se arrepiente; Dios le enseña su compasión."],

["Miqueas",1,3,"Miqueas denuncia la injusticia de los líderes y profetas corruptos de Israel y Judá, y anuncia el juicio sobre Samaria y Jerusalén."],
["Miqueas",4,7,"Promesa del monte del Señor y del gobernante que nacerá en Belén; Dios pide justicia, misericordia y humildad, y perdona el pecado."],

["Nahúm",1,3,"Nahúm anuncia la caída de Nínive; Dios es justo y poderoso, y libra a su pueblo del opresor asirio que será destruido."],

["Habacuc",1,3,"Habacuc cuestiona a Dios por la injusticia; aprende que el justo vivirá por su fe, y termina confiando y gozándose en el Señor."],

["Sofonías",1,3,"Sofonías anuncia el día del Señor sobre Judá y las naciones; tras el juicio, Dios promete un remanente y se regocijará sobre su pueblo."],

["Hageo",1,2,"Hageo anima al pueblo a reconstruir el templo en lugar de descuidarlo; Dios promete su presencia y bendición a quienes obedecen."],

["Zacarías",1,3,"Visiones nocturnas de consuelo y restauración; Dios volverá a Jerusalén, reconstruirá su casa y limpiará al sumo sacerdote."],
["Zacarías",4,6,"Más visiones: el candelabro, los rollos y los carros; 'no con ejército ni con fuerza, sino con mi Espíritu', dice el Señor."],
["Zacarías",7,9,"Dios pide justicia verdadera, no ayunos vacíos; promete restaurar Jerusalén y anuncia al Rey humilde que vendrá sobre un asno."],
["Zacarías",10,12,"Dios cuidará a su rebaño; un mensaje sobre el pastor rechazado, y la promesa de derramar espíritu de gracia sobre Jerusalén."],
["Zacarías",13,14,"Se abrirá una fuente de purificación; tras el juicio final, el Señor reinará como rey sobre toda la tierra."],

["Malaquías",1,4,"Malaquías reprende al pueblo y a los sacerdotes por su culto despreciativo y su infidelidad; anuncia al mensajero y el día del Señor."]
];
