// PLAN ANUAL COMPLETO — 395 días recorriendo toda la Biblia.
// Cada entrada: [book, c1, c2, "resumen breve"]
// Generado con rangos fijos de ~3 capítulos. Resúmenes fieles al contenido.
// Parte A: Génesis a Ester (días 1-143)
const PLAN_FULL_A = [
["Génesis",1,3,"Dios crea el mundo y lo declara bueno, forma al ser humano a su imagen; la desobediencia introduce el pecado y la separación de Dios."],
["Génesis",4,6,"Caín mata a Abel y la maldad se extiende sobre la tierra; entre la corrupción creciente, Noé halla gracia ante los ojos de Dios."],
["Génesis",7,9,"El diluvio cubre la tierra y solo se salva el arca; al bajar las aguas, Dios establece su pacto con la señal del arcoíris."],
["Génesis",10,12,"Las naciones se reparten y en Babel se dispersan por su orgullo; Dios llama a Abram con la promesa de bendecir a todos los pueblos."],
["Génesis",13,15,"Abram y Lot se separan; Abram rescata a Lot y es bendecido por Melquisedec; Dios promete descendencia y sella un pacto con él."],
["Génesis",16,18,"Nace Ismael de Agar; Dios renueva el pacto y la circuncisión, promete un hijo a Sara, y anuncia el juicio sobre Sodoma."],
["Génesis",19,21,"Sodoma y Gomorra son destruidas y Lot es librado; nace Isaac, el hijo de la promesa, y Agar e Ismael son cuidados por Dios."],
["Génesis",22,24,"Dios prueba a Abraham pidiéndole a Isaac y provee un sustituto; muere Sara, y se busca esposa para Isaac, hallando a Rebeca."],
["Génesis",25,27,"Mueren Abraham; nacen Esaú y Jacob que rivalizan; Jacob obtiene la primogenitura y, con engaño, la bendición de Isaac."],
["Génesis",28,30,"Jacob sueña con la escalera y recibe el pacto; trabaja por Raquel y Lea, forma una gran familia y prospera con los rebaños."],
["Génesis",31,33,"Jacob huye de Labán, lucha con Dios y es renombrado Israel; se reconcilia con su hermano Esaú tras años de temor."],
["Génesis",34,36,"La violencia mancha a la familia en Siquem; Dios reafirma el pacto en Betel; mueren Raquel e Isaac, y se enumeran los descendientes de Esaú."],
["Génesis",37,39,"José, el favorito, es vendido por sus hermanos por envidia; entre la historia de Judá y Tamar, resiste la tentación en Egipto."],
["Génesis",40,42,"José interpreta sueños en la cárcel y luego los del faraón, llegando a gobernar Egipto; el hambre lleva a sus hermanos ante él."],
["Génesis",43,45,"Los hermanos vuelven con Benjamín; José los pone a prueba y se da a conocer entre lágrimas, perdonando el mal recibido."],
["Génesis",46,48,"Jacob baja a Egipto y se reencuentra con José; se establece en Gosén, y Jacob bendice a los hijos de José antes de morir."],
["Génesis",49,50,"Jacob bendice a sus doce hijos y muere; José asegura que Dios encaminó el mal para bien, y muere con la esperanza de la promesa."],

["Éxodo",1,3,"Israel crece esclavizado en Egipto; nace Moisés y es salvado de las aguas; Dios lo llama desde la zarza ardiente para liberar a su pueblo."],
["Éxodo",4,6,"Moisés vuelve con señales pero el faraón endurece la esclavitud; Dios reafirma su pacto y su promesa de liberación a Israel."],
["Éxodo",7,9,"Comienzan las plagas sobre Egipto: sangre, ranas, piojos, moscas, peste, úlceras y granizo, mientras el faraón se obstina."],
["Éxodo",10,12,"Langostas y tinieblas golpean Egipto; Dios instituye la Pascua, y con la muerte de los primogénitos el faraón deja salir a Israel."],
["Éxodo",13,15,"Dios guía con nube y fuego, abre el mar para que crucen y destruye al ejército egipcio; Israel canta su liberación."],
["Éxodo",16,18,"En el desierto Dios provee maná, codornices y agua; Israel vence a Amalec y Jetro aconseja a Moisés delegar el gobierno."],
["Éxodo",19,21,"En el Sinaí Dios desciende y entrega los Diez Mandamientos; comienzan las leyes que ordenan la justicia y la vida del pueblo."],
["Éxodo",22,24,"Más leyes sobre la convivencia y las fiestas; el pueblo acepta el pacto y Moisés sube al monte ante la gloria de Dios."],
["Éxodo",25,27,"Dios da instrucciones para el tabernáculo: el arca, la mesa, el candelabro, las cortinas y el altar, lugar de su presencia."],
["Éxodo",28,30,"Se describen las vestiduras y la consagración de los sacerdotes, y los elementos del culto para acercarse a Dios con santidad."],
["Éxodo",31,33,"Israel adora el becerro de oro; Moisés intercede ante la ira de Dios, quien renueva su compromiso y muestra su gloria."],
["Éxodo",34,36,"Dios renueva el pacto y las tablas; el pueblo ofrenda con generosidad y los artesanos comienzan a construir el tabernáculo."],
["Éxodo",37,40,"Se completan los muebles y el tabernáculo conforme a lo ordenado; al levantarlo, la gloria de Dios lo llena y guía a Israel."],

["Levítico",1,3,"Dios establece los sacrificios: holocausto, ofrenda y de paz, formas de acercarse a él, dar gracias y mantener la comunión."],
["Levítico",4,6,"Leyes sobre el sacrificio por el pecado y la culpa, y los deberes de los sacerdotes en el manejo de las ofrendas."],
["Levítico",7,9,"Se completan las normas de los sacrificios; Aarón y sus hijos son consagrados y comienza el ministerio sacerdotal."],
["Levítico",10,12,"La muerte de Nadab y Abiú advierte sobre la santidad; se distingue lo limpio de lo inmundo en los alimentos y la purificación."],
["Levítico",13,15,"Normas sobre enfermedades de la piel, la lepra y las impurezas del cuerpo, con ritos para restaurar la comunión con Dios."],
["Levítico",16,18,"El Día de la Expiación limpia al pueblo; Dios llama a la santidad en la sangre y en las relaciones, apartándose de lo pagano."],
["Levítico",19,21,"Leyes de santidad práctica: amar al prójimo, justicia, respeto; normas para los sacerdotes que representan a Dios ante el pueblo."],
["Levítico",22,24,"Sobre la santidad de las ofrendas y las fiestas del Señor: Pascua, Pentecostés, Trompetas, Expiación y Tabernáculos."],
["Levítico",25,27,"El año sabático y el jubileo; Dios promete bendición por la obediencia, advierte la rebeldía, y norma los votos consagrados."],

["Números",1,3,"Se censa al pueblo y se organiza el campamento por tribus; los levitas son apartados para el servicio del tabernáculo."],
["Números",4,6,"Deberes de los levitas, leyes de pureza, la bendición sacerdotal y el voto nazareo, marcando la vida consagrada a Dios."],
["Números",7,9,"Ofrendas de los líderes y consagración de los levitas; se celebra la segunda Pascua y la nube guía cuándo marchar."],
["Números",10,12,"Israel parte del Sinaí; el pueblo se queja por la comida, Moisés se agota, y Miriam y Aarón cuestionan su liderazgo."],
["Números",13,15,"Doce espías exploran Canaán; el miedo y la incredulidad llevan a Israel a vagar cuarenta años por el desierto."],
["Números",16,18,"La rebelión de Coré es juzgada; la vara de Aarón reverdece confirmando su sacerdocio, y se definen los deberes sacerdotales."],
["Números",19,21,"Leyes de purificación; muere Miriam, Moisés golpea la roca, y el pueblo es sanado al mirar la serpiente de bronce."],
["Números",22,24,"Balac contrata a Balaam para maldecir a Israel, pero Dios convierte sus palabras en bendición una y otra vez."],
["Números",25,27,"El pecado en Baal-peor trae juicio; un nuevo censo, las hijas de Zelofehad reclaman herencia, y Josué es designado sucesor."],
["Números",28,30,"Calendario de ofrendas diarias, sabáticas y de las fiestas; leyes sobre los votos, especialmente de las mujeres."],
["Números",31,33,"Guerra contra Madián, reparto de tierra al oriente del Jordán y recuento de las etapas del viaje desde Egipto."],
["Números",34,36,"Se fijan los límites de la tierra prometida, las ciudades de refugio y leyes de herencia para conservar las tribus."],

["Deuteronomio",1,3,"Moisés repasa el viaje desde Horeb: la rebeldía en Cades, los años en el desierto y las victorias al oriente del Jordán."],
["Deuteronomio",4,6,"Moisés llama a obedecer y no olvidar a Dios; repite los Diez Mandamientos y el Shemá: amar a Dios con todo el corazón."],
["Deuteronomio",7,9,"Israel debe rechazar la idolatría y recordar que Dios lo eligió por gracia, no por mérito, y le dio la tierra prometida."],
["Deuteronomio",10,12,"Moisés recuerda el amor y las exigencias de Dios, llama a la gratitud y ordena adorar solo donde Dios escoja poner su nombre."],
["Deuteronomio",13,15,"Advertencias contra la idolatría; leyes sobre alimentos, diezmos, el año de remisión y el cuidado de los esclavos y pobres."],
["Deuteronomio",16,18,"Las fiestas anuales y normas sobre reyes, sacerdotes y profetas; se anuncia un profeta como Moisés que Dios levantará."],
["Deuteronomio",19,21,"Ciudades de refugio, justicia en los tribunales, conducta en la guerra y leyes para la vida en la tierra prometida."],
["Deuteronomio",22,24,"Leyes diversas sobre la familia, la propiedad, la justicia social y el cuidado del prójimo y del más vulnerable."],
["Deuteronomio",25,27,"Más leyes de equidad y la ofrenda de primicias; se ordena escribir la ley en piedras al entrar a la tierra."],
["Deuteronomio",28,30,"Bendiciones por obedecer y maldiciones por abandonar a Dios; Moisés llama a escoger la vida y a volver al Señor de corazón."],
["Deuteronomio",31,34,"Moisés comisiona a Josué, entrega su cántico y bendice a las tribus; contempla la tierra desde el Nebo y muere allí."],

["Josué",1,3,"Dios anima a Josué a ser fuerte y valiente; Rahab esconde a los espías, e Israel cruza el Jordán que se detiene milagrosamente."],
["Josué",4,6,"Se levantan doce piedras como memorial; el pueblo se consagra y los muros de Jericó caen tras marchar por orden de Dios."],
["Josué",7,9,"El pecado de Acán trae derrota en Hai; tras corregirlo, Israel vence, renueva el pacto, pero es engañado por los gabaonitas."],
["Josué",10,12,"Dios pelea por Israel deteniendo el sol; se conquistan los reinos del sur y del norte, y se enumeran los reyes vencidos."],
["Josué",13,15,"Comienza el reparto de la tierra entre las tribus; Caleb recibe Hebrón por su fe, y se describe el territorio de Judá."],
["Josué",16,18,"Continúa el reparto entre las tribus; se establece el tabernáculo en Silo y se delimitan las heredades restantes."],
["Josué",19,21,"Se completa el reparto de la tierra; se designan ciudades de refugio y ciudades para los levitas en todo Israel."],
["Josué",22,24,"Las tribus del oriente regresan y un altar casi provoca conflicto; Josué se despide renovando el pacto en Siquem y muere."],

["Jueces",1,3,"Israel no expulsa del todo a los cananeos y cae en idolatría; Dios levanta los primeros jueces para librar al pueblo."],
["Jueces",4,6,"Débora y Barac vencen a Sísara y celebran con un cántico; el pueblo recae, y Dios llama a Gedeón con señales."],
["Jueces",7,9,"Gedeón vence a Madián con solo trescientos hombres; tras su muerte, su hijo Abimelec usurpa el poder con violencia y cae."],
["Jueces",10,12,"Jefté libra a Israel pero hace un voto trágico; siguen conflictos entre las tribus y el ministerio de jueces menores."],
["Jueces",13,15,"Nace Sansón, consagrado como nazareo; con fuerza extraordinaria enfrenta a los filisteos, marcado por sus pasiones."],
["Jueces",16,18,"Sansón cae por Dalila pero vence al morir; comienza la decadencia espiritual con la idolatría de Micaía y la tribu de Dan."],
["Jueces",19,21,"Un crimen atroz desata guerra civil contra Benjamín; el libro cierra mostrando el caos cuando cada uno hacía lo que quería."],

["Rut",1,4,"En tiempos de los jueces, Rut la moabita acompaña fielmente a Noemí; Booz la redime y se casa con ella, entrando en la línea de David."],

["1 Samuel",1,3,"Ana ora con angustia y nace Samuel, dedicado a Dios; mientras los hijos de Elí pecan, Dios llama al niño Samuel como profeta."],
["1 Samuel",4,6,"Los filisteos capturan el arca, pero esta causa estragos entre ellos y es devuelta con temor al territorio de Israel."],
["1 Samuel",7,9,"Samuel guía al pueblo al arrepentimiento; Israel pide un rey, y Dios dirige a Samuel para ungir a Saúl."],
["1 Samuel",10,12,"Saúl es ungido y confirmado rey al librar a Jabes de Galaad; Samuel advierte al pueblo sobre la obediencia a Dios."],
["1 Samuel",13,15,"Saúl falla al ofrecer sacrificio y desobedecer a Dios; es rechazado como rey, mientras Jonatán muestra fe valiente."],
["1 Samuel",16,18,"Samuel unge en secreto a David, quien vence a Goliat con fe; su triunfo despierta la creciente envidia de Saúl."],
["1 Samuel",19,21,"Saúl intenta matar a David, que huye con la ayuda de Jonatán y Mical; comienza su largo tiempo de fugitivo."],
["1 Samuel",22,24,"David reúne seguidores y huye de Saúl; en una cueva le perdona la vida, negándose a alzar la mano contra el ungido de Dios."],
["1 Samuel",25,27,"Abigail evita un derramamiento de sangre; David vuelve a perdonar a Saúl y, agotado, se refugia entre los filisteos."],
["1 Samuel",28,31,"Saúl consulta a una adivina ante el temor; los filisteos atacan, y Saúl y Jonatán mueren en batalla en el monte Gilboa."],

["2 Samuel",1,3,"David lamenta la muerte de Saúl y Jonatán; es ungido rey de Judá, mientras una larga guerra civil divide a Israel."],
["2 Samuel",4,6,"David reina sobre todo Israel, toma Jerusalén y lleva el arca a la ciudad con gran gozo y adoración."],
["2 Samuel",7,9,"Dios promete a David una dinastía eterna; el rey extiende su reino y muestra bondad con Mefiboset, hijo de Jonatán."],
["2 Samuel",10,12,"David cae en adulterio con Betsabé y ordena la muerte de Urías; Natán lo confronta y David se arrepiente."],
["2 Samuel",13,15,"Las consecuencias del pecado golpean a la familia de David con violencia; Absalón se rebela y David huye de Jerusalén."],
["2 Samuel",16,18,"Entre traiciones y lealtades, Dios frustra el consejo de los rebeldes; Absalón muere y David lo llora profundamente."],
["2 Samuel",19,21,"David regresa a Jerusalén entre tensiones entre las tribus; se resuelven conflictos y una hambruna por el pacto quebrantado."],
["2 Samuel",22,24,"David canta un salmo de gratitud y recuerda a sus valientes; un censo orgulloso trae juicio, y levanta un altar donde habrá un templo."],

["1 Reyes",1,3,"Salomón llega al trono y consolida el reino; pide a Dios sabiduría para gobernar, y la demuestra en un juicio célebre."],
["1 Reyes",4,6,"Salomón gobierna con prosperidad y sabiduría, y comienza a construir el templo de Jerusalén con gran esplendor."],
["1 Reyes",7,9,"Salomón termina el templo y su palacio; al dedicarlo, la gloria de Dios lo llena, y el Señor renueva sus promesas y advertencias."],
["1 Reyes",10,12,"La fama de Salomón se extiende, pero la idolatría lo desvía; tras su muerte el reino se divide en norte y sur."],
["1 Reyes",13,15,"Jeroboán lleva al norte a la idolatría; se suceden reyes en Judá e Israel, la mayoría infieles a Dios."],
["1 Reyes",16,18,"La maldad crece hasta Acab y Jezabel; Elías anuncia sequía y vence a los profetas de Baal en el monte Carmelo."],
["1 Reyes",19,22,"Elías se encuentra con Dios en el silencio y llama a Eliseo; Acab peca por la viña de Nabot y muere en batalla como se profetizó."],

["2 Reyes",1,3,"Elías es llevado al cielo y Eliseo recibe su manto y poder; comienzan sus milagros al servicio del pueblo de Dios."],
["2 Reyes",4,6,"Eliseo multiplica aceite, resucita a un niño, sana a Naamán de lepra y muestra el poder de Dios en medio de la guerra."],
["2 Reyes",7,9,"Dios libra a Samaria del sitio; Jehú es ungido para ejecutar juicio sobre la casa idólatra de Acab."],
["2 Reyes",10,12,"Jehú extermina la adoración de Baal; Joás repara el templo, y la historia alterna reyes fieles e infieles."],
["2 Reyes",13,15,"Tras varios reyes inconstantes en ambos reinos, la idolatría persiste y el reino del norte se debilita ante Asiria."],
["2 Reyes",16,18,"El reino del norte cae ante Asiria por su idolatría y el pueblo es deportado; Ezequías reina con fidelidad en Judá."],
["2 Reyes",19,21,"Jerusalén es librada milagrosamente de Asiria; Ezequías es sanado, pero Manasés lleva luego a Judá a la maldad."],
["2 Reyes",22,25,"El joven Josías halla la ley y lidera una reforma; tras él, Judá cae, Jerusalén y el templo son destruidos por Babilonia."],

["1 Crónicas",1,3,"Genealogías desde Adán hasta las tribus de Israel y la línea de David, mostrando la continuidad del plan de Dios."],
["1 Crónicas",4,6,"Continúan las genealogías de las tribus, incluyendo a Leví y los sacerdotes, destacando el orden del pueblo de Dios."],
["1 Crónicas",7,9,"Más genealogías de las tribus y de los que regresaron del exilio, enfatizando la identidad y el culto restaurado."],
["1 Crónicas",10,12,"Muere Saúl; David es proclamado rey por todo Israel, conquista Jerusalén y reúne a sus valientes."],
["1 Crónicas",13,15,"David lleva el arca a Jerusalén; tras una primera tentativa fallida, lo hace con orden y gozo según la ley."],
["1 Crónicas",16,18,"David organiza la alabanza y entona un cántico de gratitud; Dios le promete una dinastía eterna y le da victorias."],
["1 Crónicas",19,21,"David extiende el reino con victorias; un censo orgulloso trae juicio, y David levanta un altar en el lugar del futuro templo."],
["1 Crónicas",22,24,"David prepara los materiales para el templo y encarga la obra a Salomón; organiza a los levitas y a los sacerdotes."],
["1 Crónicas",25,27,"David organiza a los músicos, porteros, tesoreros y oficiales del reino para el servicio ordenado de la casa de Dios."],
["1 Crónicas",28,29,"David encarga a Salomón construir el templo, entrega los planos y ofrenda con generosidad; el pueblo da con alegría y muere David."],

["2 Crónicas",1,3,"Salomón pide sabiduría y comienza a construir el templo en Jerusalén, en el monte donde Dios se apareció a David."],
["2 Crónicas",4,6,"Se completan los utensilios del templo; al llevar el arca, la gloria de Dios lo llena, y Salomón ora en su dedicación."],
["2 Crónicas",7,9,"Fuego del cielo confirma el templo; Dios promete sanar la tierra si el pueblo se humilla; la fama de Salomón se extiende."],
["2 Crónicas",10,12,"El reino se divide tras Salomón; Roboán y los primeros reyes alternan entre la fidelidad y el abandono de Dios."],
["2 Crónicas",13,15,"Abías y Asa confían en Dios y obtienen victoria; Asa trae reformas y es animado a buscar al Señor de todo corazón."],
["2 Crónicas",16,18,"Asa falla al final por confiar en alianzas; Josafat busca a Dios y prospera, aunque se alía imprudentemente con Acab."],
["2 Crónicas",19,21,"Josafat reforma la justicia y, ante la amenaza, ora y Dios da la victoria sin pelear; luego reinan reyes menos fieles."],
["2 Crónicas",22,24,"La usurpadora Atalía amenaza la línea de David; el niño Joás es salvado y, guiado por el sacerdote, restaura el templo."],
["2 Crónicas",25,27,"Amasías, Uzías y Jotam alternan entre buscar a Dios y caer en orgullo, con consecuencias para ellos y el pueblo."],
["2 Crónicas",28,30,"Acaz lleva a Judá a la idolatría; su hijo Ezequías purifica el templo, restaura el culto y celebra una gran Pascua."],
["2 Crónicas",31,33,"Ezequías ordena el culto y Dios lo libra de Asiria; Manasés peca gravemente pero se arrepiente al final de su vida."],
["2 Crónicas",34,36,"Josías halla la ley e inicia una reforma con una gran Pascua; tras él, Judá cae y Jerusalén es destruida, pero se anuncia el regreso."],

["Esdras",1,3,"Ciro permite el regreso del exilio; los judíos vuelven, reconstruyen el altar y ponen los cimientos del nuevo templo."],
["Esdras",4,6,"La oposición detiene la obra, pero los profetas animan a continuar y el templo se termina y se dedica con gozo."],
["Esdras",7,10,"Esdras regresa con un grupo para enseñar la ley, y enfrenta el problema de los matrimonios mixtos con oración y arrepentimiento."],

["Nehemías",1,3,"Nehemías se entristece por Jerusalén, ora y obtiene permiso para volver; organiza al pueblo para reconstruir los muros."],
["Nehemías",4,6,"Pese a la oposición y las amenazas, el muro se completa con perseverancia; Nehemías corrige injusticias entre el pueblo."],
["Nehemías",7,9,"Esdras lee la ley y el pueblo escucha con reverencia y llanto; se confiesan los pecados y se recuerda la fidelidad de Dios."],
["Nehemías",10,13,"El pueblo renueva el pacto, se repuebla Jerusalén y se dedica el muro; Nehemías reforma los abusos para mantener la fidelidad."],

["Ester",1,3,"En Persia, Ester llega a ser reina sin revelar su origen judío; Amán trama un decreto para exterminar a los judíos."],
["Ester",4,6,"Mardoqueo pide ayuda a Ester, que arriesga su vida ante el rey; en un giro providencial, Amán es obligado a honrar a Mardoqueo."],
["Ester",7,10,"Ester revela el complot, Amán cae en su propia trampa, los judíos se defienden y triunfan, y se instituye la fiesta de Purim."]
];
